server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: auth-service
          uri: lb://AUTH-SERVICE
          predicates:
            - Path=/api/auth/**
        - id: order-service
          uri: lb://ORDER-SERVICE
          predicates:
            - Path=/api/orders/**
        - id: item-service
          uri: lb://ITEM-SERVICE
          predicates:
            - Path=/api/items/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/ 